language: crystal
branches:
  only:
  - master
  - dev
env:
  global:
    - ES_VERSION=5.1.1
    - ES_PORT=9200
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - SOEGEN_ES_CMD=/tmp/elasticsearch-$ES_VERSION/bin/elasticsearch
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.1.deb
  - sudo dpkg -i --force-confnew elasticsearch-5.1.1.deb
  - sudo service elasticsearch start
  - sleep 5
